### ISSUE TITLE
LVM coommand errors in lshell environment under root

### ISSUE THREAD

**Issue by jfucanada** [ghantoos/lshell#106]
I got errors when I ran LVM commands in lshell environment under root. Any idea?

root@test(fake):~$ vgs
File descriptor 3 (/var/log/lshell/20150711-root.log) leaked on vgs invocation. Parent PID 103083: /usr/bin/python
File descriptor 4 (/etc/gshadow) leaked on vgs invocation. Parent PID 103083: /usr/bin/python
  VG        #PV #LV #SN Attr   VSize   VFree
  cernervg    1   9   0 wz--n-  96.00G 14.40G
  cernmckvg   1  10   0 wz--n-  96.00G 14.00G
  cerntr1vg   1  10   0 wz--n-  96.00G 14.00G
  oraclevg    1   6   0 wz--n-  32.00G  5.00G
  swapvg      1   1   0 wz--n-  64.00G     0
  vg00        1  11   0 wz--n- 135.69G 74.69G
root@test(fake):~$

root@test(mockbc):~$ pvs
File descriptor 3 (/var/log/lshell/20150711-root.log) leaked on pvs invocation. Parent PID 103083: /usr/bin/python
File descriptor 4 (/etc/gshadow) leaked on pvs invocation. Parent PID 103083: /usr/bin/python
  PV                    VG        Fmt  Attr PSize   PFree
  /dev/cciss/c0d0p2     vg00      lvm2 a--  135.69G 74.69G
  /dev/mpath/mpath100p1 swapvg    lvm2 a--   64.00G     0
  /dev/mpath/mpath101p1 cernmckvg lvm2 a--   96.00G 14.00G
  /dev/mpath/mpath102p1 oraclevg  lvm2 a--   32.00G  5.00G
  /dev/mpath/mpath103p1 cerntr1vg lvm2 a--   96.00G 14.00G
  /dev/mpath/mpath104p1 cernervg  lvm2 a--   96.00G 14.40G
root@test(fake):~$

**Comment by ghantoos** [comment]
This looks like a bug with the way lvm; https://bugzilla.redhat.com/show_bug.cgi?id=628450#c3

You can set LVM_SUPPRESS_FD_WARNINGS to suppress these warnings: https://bugs.launchpad.net/ubuntu/+source/lvm2/+bug/591823

Other links can be found on these 2 bug reports.

Another solution, is to disable logging in the lshell configuration, but I'm not sure it's the best solution. :)

I hope this helps.

**Comment by jfucanada** [comment]
Thanks.
