### ISSUE TITLE
Run lshell on CentOS 6.7

### ISSUE THREAD

**Issue by zarr12steven** [ghantoos/lshell#111]
Environment: CentOS 6.7
Run lshell version: lshell-0.9.14 - Limited Shell

**Q1: When I comment `#forbidden`, and user login the server show below**

```
ERROR: Missing parameter 'forbidden'
ERROR: Add it in the in the [foo] or [default] section of conf file.
```
**Q2: When I change lshell.conf, how to reload the config to effect already login user ? I try it arleady, but it's not work, the user have to logout, and login again, Have any other way can to do this ?**

**Comment by ghantoos** [comment]
>
> *Q1: When I comment #forbidden, and user login the server show below*
>
> ERROR: Missing parameter 'forbidden'
> ERROR: Add it in the in the [foo] or [default] section of conf file.
>
> forbidden is a mandatory parameter. You can just set it to [].

*Q2: When I change lshell.conf, how to reload the config to effect already
> login user ? I try it arleady, but it's not work, the user have to logout,
> and login again, Have any other way can to do this ?*
>
 This use to work in version 0.9.15 (I believe). I will check it out, but
this feature is not included in the version you are using.
