### ISSUE TITLE
custom prompt options

### ISSUE THREAD

**Issue by lmarkov** [ghantoos/lshell#114]
Is there a way to configure more detailed prompt information? Using this options:

```
##  configure your promt using %u or %h (default: username)
prompt          : "%u@%h"

##  set sort prompt current directory update (default: 0)
prompt_short    : 1
```

the path looks like:
```
root@myserver: public_html$ pwd
/home/myuser/public_html
```
I want to see the information from pwd for example:
```
root@myserver: /home/myuser/public_html$ 
```
Is it possible?

**Comment by ghantoos** [comment]
The reference point is the home directory of the user. It is not possible to do this with the current code. I will set this as wishlist. If you have time to propose a patch. ;)

**Comment by lmarkov** [comment]
I added this:

#in
def updateprompt(self, path):

# new condition
elif self.conf['prompt_short'] == 2:
            self.prompt = '%s:%s:$ ' % (self.promptbase, os.getcwd())

In my configuration file I use:
##  set sort prompt current directory update (default: 0)
prompt_short    : 2

In my configuration this works for me.

**Comment by ghantoos** [comment]
Thanks! I'll look into this.

**Comment by lmarkov** [comment]
Hello,

Is there option to see the path for symlink instead the real path. For example I have symlink in directory /home/myuser
```
access-logs -> /usr/local/apache/domlogs/myuser
```
and when I enter with:
```
cd access-logs
```
the result in pwd is 
```
/usr/local/apache/domlogs/jadoreb
```
instead:
```
/home/myuser/access-logs
```
Can you suggest some solution?

**Comment by ghantoos** [comment]
@lmarkov I have opened a new issue here: https://github.com/ghantoos/lshell/issues/134

I will need to look into this bug, as what you are asking is currently not possible to achieve.

Thanks for the report!
