### ISSUE TITLE
unknown syntax

### ISSUE THREAD

**Issue by lmarkov** [ghantoos/lshell#115]
Hello,

When I make test instead of unknown syntax I always receive *** forbidden command. For example:

```
:~$ bla
*** forbidden command: bla
```

Can you suggest what I have to change in my configuration?

Parameter "strict" is set to 0 and "warnings" is -1.

**Comment by ghantoos** [comment]
Hi,

By default, lshell considers all unknown commands as forbidden. If the command is not allowed, then it's considered forbidden.

I hope this clears it for you.

Cheers
