### ISSUE TITLE
more than one login_script

### ISSUE THREAD

**Issue by lmarkov** [ghantoos/lshell#120]
Hello,

Can you tell is there a way to load several scripts with login_script in the conf file?

**Comment by ghantoos** [comment]
Unfortunately, I'm not sure there is. May be it would be easier to combine your multiple scripts into one wrapper script?

**Comment by lmarkov** [comment]
I have one custom script for autocomplete with command 
```
complete -W
```
but it is not recognized at all. I try to manually use it but there is no result. It is in allowed commands in the configuration file.

**Comment by ghantoos** [comment]
This will only work for bash, the completion is completely re-implemented in lshell. This should explain why your command is not recognized.

**Comment by lmarkov** [comment]
Hello,

Could you suggest me alternative way to create custom tab autocomplete options for script? 

For example I have python script called 'myscript' and it has to use options from argparse like --user --check etc. 

Example:
```
bash> myscript [tab tab]
--user --check
```

Thank you in advance.
