### ISSUE TITLE
Can lshell be a full replacement to ZSH? Are Python being slower a myth or reality in lshell?

### ISSUE THREAD

**Issue by timofonic** [ghantoos/lshell#125]
Hello.

I'm very interested in lshell. It would be quite interesting if joining it with MOSH and my typical usage of certain ZSH features (complete, associate file types to be opened in certain apps directly, custom colors and prompt, etc).

What about the common talk about Python being inappropriate for software like a shell? There were other attempts of rewiring lshell to C, but none were successful.

Kind regards.

**Comment by ghantoos** [comment]
Hi @timofonic !

There are much less features in lshell, compared to zsh. The intent of lshell is to restrict some users on your server/infra, not to replace a full-scale shell. You can give it a try, but in my opinion, you might not find it easy to replace you main shell.

As for Python, it is of course slower than if coded in C. There was an attempt from a friend to do so a couple of years back, but the project was abandoned: https://github.com/joehakimrahme/Agros
For the kind of use lshell is intended to, the overhead that Python adds is very supportable. Of course, if you start using it as you use bash/sh/zsh/etc, then you might find it (much) slower in some cases.

Does this answer your interrogation?

Cheers
