### ISSUE TITLE
Yum install can't find lshell

### ISSUE THREAD

**Issue by dsalaza4** [ghantoos/lshell#128]
sudo yum install lshell

Setting up Install Process
No package lshell available.
Error: Nothing to do

**Comment by ghantoos** [comment]
Hi there,

A couple of questions:

- which package are you using? Are you building it from the spec file? 
- which distribution are you using?
- which version of lshell ?

Thanks!

**Comment by dsalaza4** [comment]
1.  What package do you mean? Spec file?
2. CentOS 6.5 Final
3. I'm just trying to install default lshell provided by yum's 3.2.29 repositories.

Can't find anything related to lshell:

me@mypc:~$ yum search lshell
Warning: No matches found for: lshell
No Matches found

**Comment by ghantoos** [comment]
You will have to add the epel repository in order to find it:
- https://apps.fedoraproject.org/packages/lshell
- https://admin.fedoraproject.org/pkgdb/package/rpms/lshell/

I hope this will help you out.

**Comment by nlhooper** [comment]
I am running CentOS 7.5 and have the same problem as OP i.e.
sudo yum install lshell 
No package lshell available.

Would you be able to elaborate on how to install the lshell epel package and / or add further CentOS installation instructions to the Wiki?

**Comment by nlhooper** [comment]
It looks like the package has been removed from the epl repository therefore I ended up downloading the rpm and installing it locally:
cd /tmp
wget https://kojipkgs.fedoraproject.org//packages/lshell/0.9.16/5.fc23/noarch/lshell-0.9.16-5.fc23.noarch.rpm
yum localinstall lshell-0.9.16-5.fc23.noarch.rpm
