### ISSUE TITLE
[PATCH]: Support for "source" in lshell for login_script

### ISSUE THREAD

**Issue by kamade** [ghantoos/lshell#129]
lshell does not have support for "source" like bash primitive. This is specially useful for login scripts that setup the lshell environment. 

The attached patch(es) have been applied in our code base and is being shared Upstream

[lshell_cgcs.patch.txt](https://github.com/ghantoos/lshell/files/159007/lshell_cgcs.patch.txt)
[lshell-source-support.patch.txt](https://github.com/ghantoos/lshell/files/159009/lshell-source-support.patch.txt)

**Comment by hostingnuggets** [comment]
@kamade I saw your patches are made against lshell v0.9.16, do you also have the same patches for version 0.9.18 available and could share them on github too? Thanks!

@ghantoos I think this feature is quite important and should have a higher priority than just wishlist.

**Comment by RandieM** [comment]
Any updates on this? It would be great if the "source" command were supported in lshell.

**Comment by LordFPL** [comment]
+1 :)
