### ISSUE TITLE
[PATCH]: Adding support for newline escape character “\” to support long commands + PS2 prompts

### ISSUE THREAD

**Issue by kamade** [ghantoos/lshell#131]
Lshell does not have any support for bash-like PS2 prompts when inputting commands that span multiple lines:

> You are in a limited shell. 
> Type '?' or 'help' to get the list of allowed commands 
> :~$ ls \ 
> images license.lic 

the “\” is ignored, ls immediately returns.

The patch adds support for recognizing a bash-like line continuation ('\') character and providing a PS2 prompt for further input. After the line continuations end, the patch appends all those segments into one command(and strips the '\' characters) before sending it to cmdparse(). This way the rest of lshell remains agnostic to the presence of line continuations and receives 1 contiguous cmd.

The attached patch has been applied in our code base and is being shared Upstream 

[lshell-newline-escape-character-support.patch.txt](https://github.com/ghantoos/lshell/files/159043/lshell-newline-escape-character-support.patch.txt)

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!

**Comment by ghantoos** [comment]
Sorry I closed this issue inadvertently. Your patch still works nearly as is. Thank you for this! I will be including it soon.
