### ISSUE TITLE
ctrl + c in htop

### ISSUE THREAD

**Issue by lmarkov** [ghantoos/lshell#140]
Hello,

When I open htop in lshell and then close it with keyboard combination - ctrl + c, the lines of the console become misplaced and everything seems blocked. I can't write in the console and have to reopen the window.

The same issue is with iotop.

**Comment by ghantoos** [comment]
Hi @lmarkov,

I can't seem to reproduce this (debian testing/unstable). What OS are you using? Version of lshell? Terminal?

**Comment by lmarkov** [comment]
I use MacOS with iTerm. The lshell is installed on different versions of CentOS. For example 6.8. Version of python is 2.6.6. I also see that when I use command python -V the console get blocked again.

![screen](https://cloud.githubusercontent.com/assets/3017169/15640276/194bb05c-263f-11e6-9b50-dc537f6b18b7.jpg)

**Comment by ghantoos** [comment]
I was able to reproduce this:

```
[vagrant@omv1 lshell]$ cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 
```

**Comment by ghantoos** [comment]
@lmarkov can you confirm that this bug is corrected using the latest code?

```
git clone https://github.com/ghantoos/lshell.git
cd lshell
export PYTHONPATH=$PWD
./bin/lshell
```

Thanks!

**Comment by lmarkov** [comment]
Yes, It seems fine now! Thank you for information.

**Comment by ghantoos** [comment]
:+1:
