### ISSUE TITLE
Change home directory

### ISSUE THREAD

**Issue by brijesh27** [ghantoos/lshell#141]
Hi, 

Is this possible with lshell, that we can read  

I have 2 users : test1 and test2 ,  test1 having lshell and i want this user can only read all files/directory under /home/test2 user and only read /etc/hosts file.

[test1]
allowed         : ['ls','pwd','cat','vim','echo','cd','vi']
warning_counter : 5
path            : ['/etc/', '/usr', '/home/test2/']
home_path       : '/home/test_user'
logpath         : /var/log/lshell/
loglevel        : 4

is this right config?

**Comment by ghantoos** [comment]
Hi @brijesh27,

You cannot restrict the user to one file (e.g. /etc/hosts). Though this might be interesting to have this feature.

Otherwise, your configuration file seems correct.

Cheers
