### ISSUE TITLE
custom autocompletion

### ISSUE THREAD

**Issue by lmarkov** [ghantoos/lshell#142]
Hello,

Is there a way to create custom autocompletions for scripts. For example in bash:

```
complete -W "bounce all" clean-mailq
```

When I use clean-mailq with tab bounce and all shows as available options

```
:~# clean-mailq
all     bounce
```

**Comment by ghantoos** [comment]
Hi @lmarkov,

There is no such feature for the moment. If you have some time to code, I would be happy to review and merge it. :) Otherwise, I will try to look into it as soon as I have some time.

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
