### ISSUE TITLE
chroot

### ISSUE THREAD

**Issue by Hodor228** [ghantoos/lshell#143]
chroot not worked...
My rule for user "admin":
[admin]
allowed: ['ls','echo','cd','ll','cp','mv']
strict: 1
warning_counter: 2
#timer: 5
chroot = '/home/admin'
path: '/home/admin/'
home_path: '/home/admin/'
scp: 1
sftp: 1
overssh: ['ls', 'rsync']

Still I can navigate through the folders /etc, /var, and so on. I thought it would be like this http://wiki.enchtex.info/howto/ssh_sftp block moving down ../admin

How to fix chroot for me?

UPD:
Version lshell-0.9.18, used WinSCP SFTP connect
Lock for SSH works good but SFTP not, the user can navigate through all the catalogs etc,var, proc, usr and so on

**Comment by Hodor228** [comment]
WinSCP sftp connect

**Comment by ghantoos** [comment]
Hi @Hodor228 

Sorry for the delay. Actually, lshell does not work with SFTP yet, only SSH. It in the todo-list, but not yet implemented. Sorry for that!

Cheer
