### ISSUE TITLE
Lshell not work with CageFS

### ISSUE THREAD

**Issue by pavelz01** [ghantoos/lshell#150]
Hello!

Unfortunately, Lshell does not work currently with CageFS.
When CageFS enabled lshell authentication not works.
In logs I see this records:
`sshd[520866]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory`

In the CageFS documentation described that /var/log/lastlog not works - http://docs.cloudlinux.com/index.html?cagefs_quirks.html

Can you lshell to prevent using /var/log/lastlog?
Enabling Lshell over CageFS can significantly improve the security.

**Comment by ghantoos** [comment]
Hello

There is an option in the configuration file to change this.

```
##  configure log file name (default is %u i.e. username.log)
#logfilename     : %y%m%d-%u
#logfilename     : syslog
```

Have you tried to change this?

**Comment by pavelz01** [comment]
Yes, I am try use the log options.
They do not solve the problem with CageFS.

**Comment by ghantoos** [comment]
I unfortunately do not have cagefs to test this. Any chance you could debug more to better understand where this comes from?
