### ISSUE TITLE
Can't run lshell under RHEL 5.11

### ISSUE THREAD

**Issue by jfucanada** [ghantoos/lshell#161]
I installed the latest version lshell on RHEL 5.11.

I got error when I ran lshell with default lshell.conf under bash.

[root@test lshell-master]# python setup.py install --no-compile --install-scripts=/usr/bin/ --record lshell-install.txt
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/lshell
copying lshell/builtins.py -> build/lib/lshell
copying lshell/shellcmd.py -> build/lib/lshell
copying lshell/checkconfig.py -> build/lib/lshell
copying lshell/sec.py -> build/lib/lshell
copying lshell/**init**.py -> build/lib/lshell
copying lshell/variables.py -> build/lib/lshell
copying lshell/utils.py -> build/lib/lshell
running build_scripts
creating build/scripts-2.4
copying and adjusting bin/lshell -> build/scripts-2.4
changing mode of build/scripts-2.4/lshell from 644 to 755
running install_lib
creating /usr/lib/python2.4/site-packages/lshell
copying build/lib/lshell/builtins.py -> /usr/lib/python2.4/site-packages/lshell
copying build/lib/lshell/shellcmd.py -> /usr/lib/python2.4/site-packages/lshell
copying build/lib/lshell/checkconfig.py -> /usr/lib/python2.4/site-packages/lshell
copying build/lib/lshell/sec.py -> /usr/lib/python2.4/site-packages/lshell
copying build/lib/lshell/**init**.py -> /usr/lib/python2.4/site-packages/lshell
copying build/lib/lshell/variables.py -> /usr/lib/python2.4/site-packages/lshell
copying build/lib/lshell/utils.py -> /usr/lib/python2.4/site-packages/lshell
running install_scripts
copying build/scripts-2.4/lshell -> /usr/bin
changing mode of /usr/bin/lshell to 755
running install_data
copying etc/lshell.conf -> /etc
copying etc/logrotate.d/lshell -> /etc/logrotate.d
creating /usr/share/doc/lshell
copying README.md -> /usr/share/doc/lshell
copying COPYING -> /usr/share/doc/lshell
copying CHANGES -> /usr/share/doc/lshell
copying man/lshell.1 -> /usr/share/man/man1/
writing list of installed files to 'lshell-install.txt'
[root@test lshell-master]# cat lshell-install.txt 
/usr/lib/python2.4/site-packages/lshell/builtins.py
/usr/lib/python2.4/site-packages/lshell/shellcmd.py
/usr/lib/python2.4/site-packages/lshell/checkconfig.py
/usr/lib/python2.4/site-packages/lshell/sec.py
/usr/lib/python2.4/site-packages/lshell/**init**.py
/usr/lib/python2.4/site-packages/lshell/variables.py
/usr/lib/python2.4/site-packages/lshell/utils.py
/usr/bin/lshell
/etc/lshell.conf
/etc/logrotate.d/lshell
/usr/share/doc/lshell/README.md
/usr/share/doc/lshell/COPYING
/usr/share/doc/lshell/CHANGES
/usr/share/man/man1/lshell.1
[root@test lshell-master]# lshell
**Traceback (most recent call last):
  File "/usr/bin/lshell", line 25, in ?
    from lshell.checkconfig import CheckConfig
  File "/usr/lib/python2.4/site-packages/lshell/checkconfig.py", line 147
    configparser.ParsingError) as argument:
                                ^**
SyntaxError: invalid syntax
[root@test lshell-master]#

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
