### ISSUE TITLE
Documentation: Update installation instructions in README.md

### ISSUE THREAD

**Issue by salamander2** [ghantoos/lshell#164]
Your instructions below fail to point out that `sudo apt-get install lshell` will install an older version, 0.9.15 to be precise. So if people want the latest version, they need to download it and install it themselves.

Also, when I last did an installation, of version 0.9.16, my instructions were `sudo python setup.py install`  . Why are there extra options now? Do I need them? 

Installation:
----------------

    1. Install from source
            # on Linux:
            python setup.py install --no-compile --install-scripts=/usr/bin/
            # on *BSD:
            python setup.py install --no-compile --install-data=/usr/{pkg,local}/
    2. On Debian (or derivatives)
            apt-get install lshell
    3.  On RHEL (or derivatives)
            yum install lshell

**Comment by salamander2** [comment]
It would also be useful to have two more sets of instructions:

1. how to upgrade from an earlier version (e.g. the 0.9.15 that gets installed by apt-get)
2. how to delete lshell (in all 3 installation methods)

**Comment by ghantoos** [comment]
Updated the README.md and installation instructions: https://github.com/ghantoos/lshell/commit/84fa5e065e374888a76802b4c0ef52f1fbf3ca62

Unfortunately official packages are not available at the moment.
