### ISSUE TITLE
Lshell with Emacs

### ISSUE THREAD

**Issue by aikane** [ghantoos/lshell#165]
Hello,

Setting up the path, like in this example:
[foo]
path            : ['/var', '/usr']

works correctly in a shell, but using an Emacs basic command Ctrl-d (Dired - Directory) opens  up an access to all folders and files, which seems to be a serious bug.

Although, Emacs respects the restrictions of the below command:
[default]
##  a list of the allowed commands or 'all' to allow all commands in user's PATH                                                               
allowed         : ['ls','echo','cd','ll','emacs', 'ssh']

which means there is some interconnectivity between Emacs and lshell.

The importance here lies in using Emacs as the IDE by the IT Teams, and a necessity of restricting an access to the folders and files.

How this trouble could be overcome?

Thanking You in advance.

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
