### ISSUE TITLE
Feature: only allow a command with parameters

### ISSUE THREAD

**Issue by dt-flo** [ghantoos/lshell#168]
Hey,

This topic sounds a little bit weird, but i think the idea behind that is appropriate. Currently when i use the following in my config:
allowed         : ['telnet']
the command "telnet" works without any problems. But now i want telnet to be restricted only to connect to localhost which can be done by "telnet localhost". So i tried to add "telnet localhost" to the only allowed command:
allowed         : ['telnet localhost']
Now when i enter "telnet localhost" the following occurs:
lshelltestacc:~$ telnet localhost
*** forbidden command: telnet

This occurs because the command "telnet" is blocked. Is there a way to only allow "telnet localhost"?

**Comment by naileakim** [comment]
I am running the same issue with the shell command `top`. I want to restrict it to: 

```shell
top -u `whoami`
```

In my config file, I added:

```
allowed : ['top -u `whoami`']
```
But I also got the `*** forbidden command` output.

**Comment by ghantoos** [comment]
This works now ;)
