### ISSUE TITLE
Package: No more lshell package for Debian

### ISSUE THREAD

**Issue by hostingnuggets** [ghantoos/lshell#173]
There is no lshell package for Debian any more since release 8.0 and now 9.0. You will have to update your README or even better provide your own .deb package ;-)

**Comment by ghantoos** [comment]
The project has been updated with important security fixes, and the latest version is now available. You can easily install it using pip from the official PyPI repository:

```bash
pip install limited-shell
```

For more details about the package: https://pypi.org/project/limited-shell/
