### ISSUE TITLE
how can i execute a binary file

### ISSUE THREAD

**Issue by HonkeeChan** [ghantoos/lshell#174]
i want to execute a binary file like '/usr/bin/file', but i fail.
`/root:~/bin$ /usr/bin/file`
`*** forbidden command: /usr/bin/file`

i think may be a can't execute the binary file, so i can't change the user.  because the /etc/shells file set the shell binary path is /usr/bin/lshell, but i can't execute the binary file using /usr/bin/lshell. 
`root:/tmp$ su cgpexpert`
`su: /usr/bin/lshell: Permission denied`

> my config file

[global]
logpath         : /var/log/lshell/                                   4: log all commands)
loglevel        : 2

[default]
allowed         :'all' + ['ll']
allowed_shell_escape        : ['man','zcat', 'find', 'vim', 'lshell']
forbidden       : [';']
warning_counter : 2
aliases         : {'ll':'ls -l', 'ls': 'ls --color=auto'}
path            : ['/', '/usr/bin', '/*']
allowed_cmd_path: ['/usr/bin']
strict          : 0

thank you so much

**Comment by zaphod77** [comment]
the entire point of lshell is to stop you from doing that. :)

this is not an issue, as near as i can tell. lshell is working as designed.

**Comment by ghantoos** [comment]
You should add `file` to the allowed list of commands.
