### ISSUE TITLE
git clone does not work with lshell

### ISSUE THREAD

**Issue by hostingnuggets** [ghantoos/lshell#175]
I have `git` and `ssh` in my list of allowed commands but still a git clone does not work with lshell. Here is the ouput:

```
git clone git@github.com:jimsalterjrs/sanoid.git
Cloning into 'sanoid'...
fatal: cannot exec 'ssh': Permission denied
fatal: unable to fork
```

**Comment by ghantoos** [comment]
Hi,

You should add `git` to the `allowed_shell_escape` setting in the configuration file.

`allowed_shell_escape        : ['git']`

I was just able to successfully clone the lshell repo:
![image](https://user-images.githubusercontent.com/477561/30668803-f424cdae-9e29-11e7-940d-42a80ad8ac09.png)

**Comment by hostingnuggets** [comment]
Thanks for the tip, that works!
