### ISSUE TITLE
can't connect with winscp and no logs

### ISSUE THREAD

**Issue by vercetty92** [ghantoos/lshell#179]
Hi,

I have just installed the latest version lshell-0.9.18 on debian. I installed it from the source, and the previous installed version was lshell-0.9.15.1.

I installed ti because apparently winscp feature coms in this version.

But I have exactly the same pb, when I connect with winscp, I have the error "you shell in not compatible, bash is recommended"

also, regarding the logs from lshell, there is nothing inside (I tried every value from 1 to 3)

 - do you know why winscp is not working?
 - do you know why there is no log?

Thx a lot in advance

Here is my lshell.conf:

`
# lshell.py configuration file
#
# $Id: lshell.conf,v 1.24 2010/04/17 23:14:58 ghantoos Exp $
[global]
##  log directory (default /var/log/lshell/ )
logpath         : /var/log/lshell/
##  set log level to 0, 1, 2 or 3  (0: no logs, 1: least verbose)
loglevel        : 1
##  configure log file name (default is %u i.e. username.log)
#logfilename     : %y%m%d-%u

[default]
##  a list of the allowed commands or 'all' to allow all commands in user's PATH
allowed         : ['ls','echo','cd','ll','bzcat','bzgrep','bzless','df','tree','cat','less','pwd','more','grep','env','shell','vi','wc']

##  a list of forbidden character or commands
forbidden       : [';', '&', '$(', '${']

##  a list of allowed command to use with sudo(8)
sudo_commands   : ['bash', 'zsh']

##  exited from lshell
#warning_counter : 10

##  command aliases list (similar to bash’s alias directive)
aliases         : {'shell':'sudo -u $USER /bin/bash', 'vi':'vim'}

##  introduction text to print (when entering lshell)
intro           : "Welcome to lshell\nYou are in a limited shell.\nType '?' or 'help' to get the list of allowed commands\n"

##  a value in seconds for the session timer
#timer           : 5

##  list of path to restrict the user "geographicaly"
path            : ['/myfolder']

##  the $HOME environment variable
#home_path       : '/myfolder'

##  update the environment variable $PATH of the user
#env_path        : ':/usr/local/bin:/usr/sbin'

##  allow or forbid the use of scp (set to 1 or 0)
#scp             : 1

## forbid scp upload
#scp_upload       : 1

## forbid scp download
#scp_download     : 1

##  allow of forbid the use of sftp (set to 1 or 0)
sftp            : 0

##  list of command allowed to execute over ssh (e.g. rsync, rdiff-backup, etc.)
overssh         : ['ls']

##  considered as unknown, and user is only warned (i.e. *** unknown synthax)
#strict          : 1

##  force files sent through scp to a specific directory
#scpforce        : '/home/bla/uploads/'

##  history file maximum size 
#history_size     : 100

##  set history file name (default is /home/%u/.lhistory)
#history_file     : "/home/%u/.lshell_history"
winscp: 1

`

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
