### ISSUE TITLE
Add color

### ISSUE THREAD

**Issue by gnujeremie** [ghantoos/lshell#18]
Hi, 
Maybe a stupid question, but is there a way to have colors in the shell output ? (The same as in bash, for example).

I can't find if it a configuration problem, or if it is just not supported yet by lshell :)

**Comment by ahillio** [comment]
I would love to be able to customize the prompt the way bash allows with PS1 (on a per-user basis, ideally).  Lshell is used by the BOA project for hosting Drupal websites, and the lack of color is challenging.  Where does this sit in the radar, now that a few years have passed?

**Comment by ahillio** [comment]
I guess this isn't a priority, but a couple years later I would still love this feature :)

**Comment by ghantoos** [comment]
Very late add, lshell now supports [terminal colour codes.](https://chrisyeh96.github.io/2020/03/28/terminal-colors.html)

```
##  configure your prompt using %u or %h (default: username)
# prompt          : "%u@%h"
##  colored prompt using ANSI escape codes colors (light red user, light cyan host)
prompt          : "\033[91m%u\033[97m@\033[96m%h\033[0m"
```

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/5c91a1f1-b93c-4ca2-8b28-726086bc42cf">
