### ISSUE TITLE
env_path before os $PATH env variable

### ISSUE THREAD

**Issue by hostingnuggets** [ghantoos/lshell#180]
For rbenv to work with lshell I need to have the `env_path` config paramter in lshell.conf config file to have precedence over the operating system `$PATH` meaning that line 577 of `checkconfig.py` which is currently:
```
os.environ['PATH'] = os.environ['PATH'] + self.conf['env_path']
```

should be for rbenv to work:
```
os.environ['PATH'] = self.conf['env_path'] + os.environ['PATH']
```

Would it be possible to add a boolean parameter in lshell.conf to define the precedence of the `env_path` parameter? It could named be something like `env_path_before_os_path` with `1` env_path would be before the os_path and with a value of `0` the opposite.

Or is there maybe another workaround this?

**Comment by brigriffin** [comment]
@ghantoos please have a look at my PR #181
