### ISSUE TITLE
Midnight Commander ignores the restrictive path and shows the entire file system

### ISSUE THREAD

**Issue by keha** [ghantoos/lshell#184]
Hello!
mc ignores /etc/lshell.conf
path: ['/var/www/site1','/var/www/site2']

PS lshell/xenial,xenial,now 0.9.17-1

**Comment by maulinglawns** [comment]
Please elaborate what you mean by ”show”. Unless you disable tab completion you will be able to enumerate the entire file system, but you shold not be able to **access** any restrictive paths.

**Comment by keha** [comment]
$ ls /
*** forbidden path -> "/"
*** You have 1 warning(s) left, before getting kicked out.
This incident has been reported
$ mc
[screenshot mc](http://i100.fastpic.ru/big/2017/1213/da/772b2955741d049da1e0a105a8d6c9da.jpg)

**Comment by ghantoos** [comment]
Allowing `mc` is like allowing `bash`. MC should be the one implementing the restrictions, I don't think that lshell can do that on their behalf.
