### ISSUE TITLE
Using words that include restricted commands fail with forbidden syntax

### ISSUE THREAD

**Issue by ghost** [ghantoos/lshell#195]
I'm restricting usage of `vi` and `vim` within `lshell`.

I'm allowing `dig` to be used.

When I attempt to `dig @davita.com <some-ip>` for example, I am unable to complete this command as the word `davita` has the restricted command `vi` listed.

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
