### ISSUE TITLE
Package: cant install lshell in amazon linux no more

### ISSUE THREAD

**Issue by Muneesh17** [ghantoos/lshell#196]
i cant install lshell in amazon linux . do lshell has been removed from epel repo?

**Comment by ZEROF** [comment]
I have feeling project is dead, removed from Debian 10 as well. Shame, this was best and easy to set.

**Comment by ghantoos** [comment]
The project has been updated with important security fixes, and the latest version is now available. You can easily install it using pip from the official PyPI repository:

```bash
pip install limited-shell
```

For more details about the package: https://pypi.org/project/limited-shell/
