### ISSUE TITLE
Unable to use SSH ProxyCommand or ProxyJump

### ISSUE THREAD

**Issue by alittlebroken** [ghantoos/lshell#202]
I have installed lshell 0.9.18 on an internal server we are using in turn to mconnect to our customers servers. 

Some of them have their own jump servers we mist go through first. We are using the SSH ProxyCommand option to allow us to go through the customer jump server direct to the target server. 

This works fine in bash but as soon as we use lshell we get the message

*** forbidden shell escape: "exec ssh -W XXX.XXX.XXX.XXX:22 btl-jump"

using ssh from within lshell to btl-jump works without any issues at all. 

I have set in the conf file the following 

allowed_shell_escape : ['git','ssh','exec']

I have also set the allowed over ssh as follows

overssh         : ['ls', 'rsync' ,'exec','ssh','git','exec']

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
