### ISSUE TITLE
Looking for co-maintainer(s) for lshell

### ISSUE THREAD

**Issue by ghantoos** [ghantoos/lshell#209]
Hello,

First of all, I would like to apologize for my lake of response over the lshell issues/PRs. I would have loved to make it evolve, but have moved on to other projects. Today, I have decided to officially ask for help in maintaining this app.

If you are interested in co-maintaining lshell, let me know and we'll work this out together.

Talk soon!

**Comment by affix** [comment]
Hey, i'd be willing to co-maintain lshell with you

**Comment by ghantoos** [comment]
Lshell has been updated to address security issues, and version 0.10 has now been released with these changes. If you notice any problems or areas that need fixing, please let me know.

Thanks again for using Lshell, and I apologize for the maintenance delay over the past few years. Have a wonderful day!
