### ISSUE TITLE
Allow git use

### ISSUE THREAD

**Issue by Drallert** [ghantoos/lshell#210]
Hello, I want to use lshell for a server to restrict access, however I need the users to be able to execute git commands. I've already enabled the "git" command in /etc/lshell.conf and some things are working (git init, git config and such, haven't tried more tough) but whenever I try to "git clone <URL>"  I get the following error:

```
fatal: cannot exec 'git-remote-https': Permission denied
```

How could I do this? Thanks in advance

**Comment by anilgopa** [comment]
What user is the lshell enabled for? Is it a non-root user? Verify if the same command runs with bash or any other shell first. It could be an issue with the user lacking enough permission to run the command irrespective of which shell is used.

**Comment by demarcq** [comment]
Did someone have fixed this issue? I have the same problem

**Comment by ghantoos** [comment]
You can use git by adding it to the `allowed_shell_escape` list instead of the `allowed` list. This will allow git to use shell escapes and won't be blocked by lshell.

lshell.conf:
```
allowed_shell_escape        : ['git']
```
