### ISSUE TITLE
failed to execute /usr/bin/lshell: Permission denied

### ISSUE THREAD

**Issue by falltodis** [ghantoos/lshell#212]
**key config :**
```[test]
allowed         : 'all' - ['su'] - ['scp']
path            : ['/var', '/usr']
home_path       : '/home/test'
```

**Install info :**
The lshell installed by root user with source  with permission
-rwxr-xr-x 1 root root xxx  /usr/bin/lshell

The test user has been changed default shell to lshell by command : `chsh -s /usr/bin/lshell`

**Problems:**
When changed user to test ,  I got a message . ssh login display same tips
`su: failed to execute /usr/bin/lshell: Permission denied`

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
