### ISSUE TITLE
Bug: allow all but some commands

### ISSUE THREAD

**Issue by NiccsJ** [ghantoos/lshell#213]
``` shell

[ori-qlab]
#allowed         : 'all' - ['su', 'aws', 'history', 'mongo', 'mongod']
allowed          : 'all' - ['su'] - ['aws'] - ['history'] - ['mongo'] - ['mongod']
#sudo_commands   : 'all'
#path           : ['/']

```

I want the user to be able to execute all but these commands. see my conf above, I've tried both ways. yet after setting it like this, lshell allows all commands.

Can someone please help me with what is the correct way of setting this?

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!

**Comment by ghantoos** [comment]
A couple of years later.. This has been fixed! :)
