### ISSUE TITLE
sftp Login Failure

### ISSUE THREAD

**Issue by fangHAOgithub** [ghantoos/lshell#250]
I added a test user, configured as lshell
I used lshell-0.10.8
The default configuration is used
Here is my configuration file
[default]
allowed         : 'all'
forbidden       : [';','&', '|','`','&gt;','&lt;', '$(','${']
scp             : 1
sftp            : 1

The sftp configured for my ssh is
Subsystem sftp /usr/libexec/openssh/sftp-server

But I was unable to connect to the test user via sftp
The following is my sftp-v log

spt@192.168.32.166's password:
debug1: Authentication succeeded (password).
Authenticated to 192.168.32.166 ([192.168.32.166]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: filesystem full
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: client_input_hostkeys: searching C:\\Users\\10273/.ssh/known_hosts for 192.168.32.166 / (none)
debug1: client_input_hostkeys: searching C:\\Users\\10273/.ssh/known_hosts2 for 192.168.32.166 / (none)
debug1: client_input_hostkeys: hostkeys file C:\\Users\\10273/.ssh/known_hosts2 does not exist
debug1: client_input_hostkeys: no new or deprecated keys from server
debug1: Sending subsystem: sftp
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2664, received 2532 bytes, in 0.6 seconds
Bytes per second: sent 4594.1, received 4366.5
Connection closed
debug1: Exit status 1

**Comment by ghantoos** [comment]
Hi @fangHAOgithub, this last code update should have fixed hat bug. Thanks for reporting this. I will make sure to release this soon in a new version.

**Comment by ghantoos** [comment]
A new version 0.10.9 was released with the fix. You can test here: https://pypi.org/project/limited-shell/
