### ISSUE TITLE
Add a list of user for sudo command

### ISSUE THREAD

**Issue by Seraf** [ghantoos/lshell#33]
Hello,

It should be great to have the -u option for sudo and set a user behind it (should be authorized in the config file, in a list).

It will allow to authorize this kind of command (for example) :
sudo -u www-data script.php

I will try to provide a patch soon.
Regards,

**Comment by ghantoos** [comment]
The -u flag is already allowed. The security/restrictions behind sudo should be configured in the sudoers configuration file, not in lshell.

To use the -u flag, just add the command in sudo_commands:
```sudo_commands: ['whoami'] ```

Then you will be able to execute it with the -u flag:
```
You are in a limited shell.
Type '?' or 'help' to get the list of allowed commands
~$ sudo -u www-data whoami
www-data
~$ sudo -u root whoami                                                                                        
root
```
