### ISSUE TITLE
sudo to all commands

### ISSUE THREAD

**Issue by jproig** [ghantoos/lshell#61]
hi, i am trying to allow a user to sudo to all commands, jus like this line in the sudoers:
oper  ALL=(ALL)       ALL

is there any way to do this?
Thanks

**Comment by ghantoos** [comment]
I've re-read and interpreted your issue. I'm not sure this is what you meant, but I found it interesting to give access to all the "allowed" commands via sudo. 

I'm committing a patch to add the possibility to set ```sudo_commands = all```, giving access to all allowed commands via sudo.
