### ISSUE TITLE
Make warnings configurable

### ISSUE THREAD

**Issue by kyrgyz** [ghantoos/lshell#7]
I really would like to change the wording of some messages, for example this one:

**\* You have 3 warning(s) left, before getting kicked out.
This incident has been reported.

Is it possible to make messages configurable?

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
