### ISSUE TITLE
lshell.conf include parameter for local config

### ISSUE THREAD

**Issue by hostingnuggets** [ghantoos/lshell#70]
It would be great if it would be possible from the lshell configuration file to include a local configuration such as a lot of Debian packages do. The goal would be to have a main lshell.conf file with standard settings and then a lshell_local.conf file where local settings could be overriden for a specific server. 

I think an option such as "include:" in the lshell.conf should be enough.

**Comment by ghantoos** [comment]
This was implemented in #59. Closing.
