### ISSUE TITLE
add source command to lshell

### ISSUE THREAD

**Issue by hostingnuggets** [ghantoos/lshell#72]
i would like my lshell users to use the virtualenv tool for hosting python, now this tool requires the user to source in a shell script using the "source" shell command as follows:

lshell$ source bin/activate

running this command simply returns:

sh: 1: source: not found

so I am guessing here that the source command is not implemented in lshell, could you implement it please? I think this is quite important to have.

**Comment by jfucanada** [comment]
There is one way to do this. You can create script to include all variables and run lshell in the end of script. It will source environmental variables with lshell. I know it's not convenient. But this could be the work around solution.

**Comment by mathieuhinderyckx** [comment]
The way I did this, was using the env_vars option in the config file:

env_vars        : {'PATH':'VIRTUAL_ENV_DIRECTORY/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'}
