### ISSUE TITLE
after installing lshell not able to login with user having default shell is lshell

### ISSUE THREAD

**Issue by unb-read** [ghantoos/lshell#76]
i am getting below error after configuring lshell for the user onlinets account.

```
[root@primeonline2 ~]# su - onlinets
Traceback (most recent call last):
  File "/usr/bin/lshell", line 27, in ?
    from lshell.checkconfig import CheckConfig
ImportError: No module named lshell.checkconfig
[root@primeonline2 ~]# uname -a
Linux primeonline2 2.6.9-42.ELsmp #1 SMP Wed Jul 12 23:27:17 EDT 2006 i686 i686 i386 GNU/Linux
[root@primeonline2 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux AS release 4 (Nahant Update 4)
[root@primeonline2 ~]# cat /etc/passwd |grep -i onlinets
onlinets:x:1027:1027::/home/onlinets:/usr/bin/lshell
```

Kindly let me know what could be the issue i have used same steps to other server who has same hardware + OS there it is working but not with this system.

**Comment by ghantoos** [comment]
We you able to resolve this issue?

**Comment by cd127** [comment]
No, unfortunately not.
I gave up and went for an alternative :/

**Comment by ghantoos** [comment]
I was re-reading the thread yesterday. I think the best to resolve this (if it is still relevant :)), is to contact the maintainer of the lshell package for your distribution. I will do my best to test this on a RHEL instance. I'm keeping the issue open till then.

Sorry you had to go with an alternative, but happy you found one. :)

**Comment by ghantoos** [comment]
Unable to reproduce with centos6+python2.6.5 fresh install. What I did:

- clone git repo
- ```python python setup.py install --no-compile --install-scripts=/usr/bin/```
- add test user and assign lshell as default shell
- ```su - test```
