### ISSUE TITLE
rbenv not compatible with lshell

### ISSUE THREAD

**Issue by hostingnuggets** [ghantoos/lshell#89]
I am using rbenv (https://github.com/sstephenson/rbenv) in order to setup my ruby environment correctly but unfortunately lshell does not work with rbenv. What I need to do to get rbenv working is to be able to execute the following command from the command line or from the lshell login_script:

eval "$(rbenv init -)"

what this does it to simply execute the following shell script commands:

```
export PATH="/home/user/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source '/home/user/.rbenv/libexec/../completions/rbenv.bash'
rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "`rbenv "sh-$command" "$@"`";;
  *)
    command rbenv "$command" "$@";;
  esac
}
```

any chances to get rbenv working with shell?

see also #77

**Comment by ghantoos** [comment]
@hostingnuggets, were you able to find a workaround for your issue?

**Comment by hostingnuggets** [comment]
unfortunately no, still impossible to use rbenv in combination with lshell

**Comment by ghantoos** [comment]
Have you tried adding

- adding the path to env_path: 
```env_path        : ':/usr/local/bin:/usr/sbin:/home/ghantoos/.rbenv/bin:/home/ghantoos/bin'```

- rbenv to the allowed commands (should be allowed_shell_escape in the latest version, as the script uses exec)

- Once you login, you can export the environment variable: ```export RBENV_SHELL=bash```

The other functions of rbenv seem to be very bash specific, which will not be compatible with lshell, as it uses subprocess which usually hit sh(1) and not bash(1).

Feel free to reopen the bug if this does not correct your behavior.

**Comment by hostingnuggets** [comment]
@ghantoos please reopen the bug as it still does not work with 0.9.18 and I can't even run a git clone, see #175, thanks!
