### ISSUE TITLE
Aliased command calls the actual command when after a pipe

### ISSUE THREAD

**Issue by brbrady** [ghantoos/lshell#96]
example:

I have this aliases line in my config:
#aliases         : {'ssh': 'limited_user_teleport', 'awk': 'gawk'}

ben:~$ ssh
usage: limited_user_teleport [-h] [-l [FILTER]] SERVER [COMMAND...]
ben:~$ echo

ben:~$ echo | ssh
usage: ssh [-1246AaCfgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
*** ssh help message cut off -- you get the point ***

While I understand that linux aliases only work at the beginning of the command, it seems like only one of the following should be true:
1. I must add an alias to 'allowed' in order for it to be allowed
2. Aliases are only aliases at the beginning of the command, failing over to use whatever is in PATH

This seems like a pretty big security flaw. I'll investigate more in the morning, maybe send a pull.

**Comment by ghantoos** [comment]
There was an error in the alias replacement function. It did not take the single pipe into account. Nice catch!
