### ISSUE TITLE
Can't use variable in cd command under lshell

### ISSUE THREAD

**Issue by jfucanada** [ghantoos/lshell#97]
Can someone help on this. Thanks.

**Comment by jfucanada** [comment]
For example, cd $HOME. LSHELL CAN't recognize $HOME variable

**Comment by jfucanada** [comment]
For example, cd $HOME. LSHELL CAN't recognize $HOME variable


s_testuser@(mockbc):~$ echo $HOME
/home/s_testuser
s_testuser@(mockbc):~$
s_testuser@test(mockbc):~$ cd $HOME
 lshell: $HOME: No such file or directory
 s_testuser@test(mockbc):~$

**Comment by jfucanada** [comment]
Got none.

**Comment by ghantoos** [comment]
I'm re-opening the issue, because this is clearly a bug, and needs to be fixed. Thanks for reporting it.

**Comment by jfucanada** [comment]
I really appreciate your help.

**Comment by jfucanada** [comment]
Thank you. It works!!
